### ISSUE TITLE
libskk v1.1.0 regression: generated header tries to find <gee.h>, but it is not in search path of major distros

### ISSUE THREAD

**Issue by hosiet** [ueno/libskk#106]
Compared with libskk v1.0.5, libskk v1.1.0 would have the following lines at the beginning of `libskk.h`:

```cpp
/* libskk.h generated by valac 0.56.18, the Vala compiler, do not modify */

#ifndef __LIBSKK_H__
#define __LIBSKK_H__

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>

G_BEGIN_DECLS
```

However, `gee.h` is not placed under `/usr/include/`, but under `/usr/include/gee-0.8/gee.h` instead in major Linux distros. This would trigger software that explicitly uses `libskk` but not explicitly uses `gee` to fail to build. For example with `fcitx5-skk`:

```
[ 68%] Built target fcitx5-skk-translation
AutoMoc: Generating "SRC:/obj-x86_64-linux-gnu/gui/fcitx5-skk-config_autogen/EWIEGA46WW/moc_main.cpp", because it doesn't exist, from "SRC:/gui/main.h"
/usr/lib/qt6/libexec/moc "-DFCITX_GETTEXT_DOMAIN=\"fcitx5-skk\"" "-DFCITX_INSTALL_LOCALEDIR=\"/usr/share/locale\"" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -D_GNU_SOURCE -Dfcitx5_skk_config_EXPORTS -I/build/reproducible-path/fcitx5-skk-5.1.9/obj-x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/Fcitx5Qt6/Fcitx5QtWidgetsAddons -I/usr/include/Fcitx5/Utils -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu --include /build/reproducible-path/fcitx5-skk-5.1.9/obj-x86_64-linux-gnu/gui/fcitx5-skk-config_autogen/moc_predefs.h --output-dep-file -o /build/reproducible-path/fcitx5-skk-5.1.9/obj-x86_64-linux-gnu/gui/fcitx5-skk-config_autogen/EWIEGA46WW/moc_main.cpp /build/reproducible-path/fcitx5-skk-5.1.9/gui/main.h
In file included from /build/reproducible-path/fcitx5-skk-5.1.9/src/skk.h:37,
                 from /build/reproducible-path/fcitx5-skk-5.1.9/src/skk.cpp:7:
/usr/include/libskk/libskk.h:10:10: fatal error: gee.h: No such file or directory
   10 | #include <gee.h>
      |          ^~~~~~~
compilation terminated.
make[3]: *** [src/CMakeFiles/skk.dir/build.make:82: src/CMakeFiles/skk.dir/skk.cpp.o] Error 1
```

`git bisect` shows that the issue was introduced in https://github.com/ueno/libskk/commit/3114245832a879c32fe98815079e7be52bf73e84 .

**Comment by ueno** [comment]
Looking more closely at the offending change, it feels to me that this might also worth fixing in libskk side. I've filed https://github.com/ueno/libskk/pull/107.
